// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrfterryvfjrzsxjxjkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyZnRlcnJ5dmZqcnpzeGp4amtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjA5MjMsImV4cCI6MjA2NjAzNjkyM30.Z8wxrZzq1WGig2XI-eIn0xLnQTYmy3uMT0FUpBDGrRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);